-- SELECT select_list
-- FROM t1
-- CROSS JOIN t2;

-- SELECT select_list
-- FROM t1,t2;

-- SELECT * FROM T1
--     INNER JOIN T2 ON true;

DROP TABLE IF EXISTS T1;
CREATE TABLE T1 (label CHAR(1) PRIMARY KEY);

DROP TABLE IF EXISTS T2;
CREATE TABLE T2 (score INT PRIMARY KEY);

INSERT INTO T1 (label)
VALUES
    ('A'),
    ('B');

INSERT INTO T2 (score)
VALUES
    (1),
    (2),
    (3);


SELECT * FROM T1
CROSS JOIN T2;